"""
search_tools.py
 
Search tool implementation for the Barrier AI FAQ assistant.
 
Wraps a fitted minsearch.Index so it can be exposed to the LLM agent as
a "search" tool: given a natural language query, it returns a ranked
list of matching documents, each enriched with a ready-to-use GitHub
citation URL.
"""

from typing import Any, Optional
import logging
from pydantic import BaseModel, Field
from minsearch import Index
from pprint import pprint

logger = logging.getLogger(__name__)

class SearchResult(BaseModel):
    content: str
    metadata: Dict[str, Any] = Field(default_factory=dict)

class SearchTool:
    """
    RAG search wrapper around a MinSearch index.

    Responsibilities:
    - Query the index
    - Enrich results with citation-ready metadata
    - Return stable dict structures for the LLM
    """

    def __init__(self, index: Index, repo_owner: str, repo_name: str, branch: str="master",num_results: int = 5):
        """
        Initialise the search tool.
 
        Args:
            index: A fitted MinSearch index to query.
            repo_owner: GitHub username or organisation that owns the repo
                being searched. Used to build citation URLs.
            repo_name: Name of the repository being searched. Used to
                build citation URLs.
            branch: The branch the indexed documents were downloaded from
                (e.g. "master" or "main"). Used to build citation URLs
                that actually resolve — should match the branch returned
                by ingest.read_repo_data, not be assumed/hardcoded.
            num_results: Maximum number of search results to return per query.
        """

        self.index = index
        self.repo_owner=repo_owner
        self.repo_name=repo_name
        self.branch=branch
        self.num_results = num_results
        self.logger = logging.getLogger(self.__class__.__name__)

    def search(self, query: str) -> list[Dict[str, Any]]:
        """
        Search the indexed documents and return citation-ready results.

        This method is registered as the agent's "search" tool (see
        search_agent.py) — its signature and return shape are what the
        LLM sees and works with directly.
 
        Args:
            query: Natural language search query, as generated by the agent.
 
        Returns:
            A list of result dicts, ranked by relevance, each containing:
            - "text": the matched document's content.
            - "path": the file's path relative to the repo root, if known.
            - "score": the relevance score assigned by the index, if any.
            - "github_url": a direct link to the source file on GitHub,
              or None if no path was available.
            - "raw": the original, unmodified result from the index,
              kept for debugging.
 
            Returns an empty list if the query is empty after cleaning,
            or if the underlying index search fails.

        """
        print("DEBUG QUERY TYPE:", type(query), query)
        # Defensively normalise the query: guards against None or
        # non-string input, and strips stray whitespace.
        query = str(query or "").strip()
        if not query:
            self.logger.warning("Empty query received")
            return []

        self.logger.info(f"SEARCH QUERY: {query}")

        try:
            results = self.index.search(query, num_results=self.num_results)
        except Exception:
            # A search failure shouldn't crash the whole agent turn —
            # log it and return no results, letting the agent's system
            # prompt handle the "no results found" case gracefully.
            self.logger.exception("Index search failed")
            return []
        
        enriched_results = []
        for r in results or []:
            # Check multiple possible key names defensively, since the
            # exact shape returned by minsearch isn't strictly guaranteed.
            # In this project, ingest.py produces "content" and "filename".
            text = r.get("text") or r.get("content") or ""
            path = r.get("path") or r.get("file") or r.get("filename") or None

            github_url = None
            if path:
                github_url = (
                    f"https://github.com/{self.repo_owner}/{self.repo_name}"
                    f"/blob/{self.branch}/{path}"
                )

            enriched_results.append({
                "text": text,
                "path": path,
                "score": r.get("score"),
                "github_url": github_url,
                "raw": r # full original record for debugging
            })
        
       

        #     structured.append(
        #         SearchResult(
        #             content=r.get("content") or r.get("text") or "",
        #             metadata=r
        #         )
        #     )
        
        # print("TOOL CALLED ✔️:", query)
        
        self.logger.info(f"SEARCH RESULTS: {len(enriched_results)}")

        # DEBUG (optional, remove later)
        for r in enriched_results:
            print("\n🔎 RESULT:")
            print("PATH:", r["path"])
            print("URL:", r["github_url"])
        
        return enriched_results
        # return structured